name: deploy
on:
  workflow_run:
    workflows: ["main"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
        node-version: [20.13]
    needs: build-and-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.HETZNER_SSH_KEY }}
    - name: Deploy to Hetzner VPS
      run: |
        rsync -avz --exclude='.git*' ./ root@${{ secrets.HETZNER_SSH_KEY }}:/path/to/your/project
    - name: Execute remote commands
      run: |
        ssh root@${{ secrets.HETZNER_SSH_KEY }} << 'EOF'
        cd /path/to/your/project
        # Add any additional commands you wish to run on the server
        # For example:
        # npm install
        # npm run build
        EOF